on: [push, pull_request]

name: CI

jobs:
  build_and_test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt-get install mesa-common-dev libx11-dev libxcursor-dev libxinerama-dev libxkbcommon-dev libxrandr-dev libxi-dev libgl1-mesa-dev
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Build BGFX Debug
        run: cargo build --verbose -F bgfx-debug
      - name: Build BGFX Release
        run: cargo build --release
      - name: Build BGFX Release + examples
        run: cargo build --release --example cubes --example helloworld
      - name: Build BGFX Debug + examples
        run: cargo build --example cubes --example helloworld
  build_emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Emscripten
        uses: mymindstorm/setup-emsdk@v11
      - name: Install emscripten Rust tools 
        run: rustup install wasm32-unknown-emscripten
      - name: Build Web example 
        run: cd web_example && cargo build --target=wasm32-unknown-emscripten 


