on: [push, pull_request]

name: CI

jobs:
  build_and_test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
     - if: matrix.os == 'ubuntu-latest'
       run: sudo apt install libwayland-cursor0 libxkbcommon-dev libwayland-dev
    - name: Build
      run: cargo build
